#!/bin/bash
# Quick View Script - Instructions for viewing your pages locally

echo "=== VIEWING YOUR NEW SITE PAGES ==="
echo ""
echo "Your files are in: /home/user/recipes/temp"
echo ""
echo "FILES CREATED:"
echo "  - index.html      (Blog homepage)"
echo "  - about.html      (About/Manifesto page)"
echo "  - recipes.html    (Recipe browser)"
echo "  - styles.css      (Shared styles)"
echo ""
echo "TO VIEW ON YOUR LOCAL COMPUTER:"
echo ""
echo "1. Download from GitHub:"
echo "   - Go to: https://github.com/chomp-chomp-pachewy/recipes"
echo "   - Switch to branch: claude/claude-md-migpu35mvu26x1q1-01EGsuwfTbt1JmZmGQGVteA2"
echo "   - Click 'Code' → 'Download ZIP'"
echo "   - Extract and navigate to the 'temp' folder"
echo "   - Double-click any .html file to open in browser"
echo ""
echo "2. Or use git clone:"
echo "   git clone https://github.com/chomp-chomp-pachewy/recipes.git"
echo "   cd recipes"
echo "   git checkout claude/claude-md-migpu35mvu26x1q1-01EGsuwfTbt1JmZmGQGVteA2"
echo "   cd temp"
echo "   open index.html  # macOS"
echo "   # or start index.html  # Windows"
echo "   # or xdg-open index.html  # Linux"
echo ""
echo "3. Alternative - Use a local web server (in the temp folder):"
echo "   cd temp"
echo "   python3 -m http.server 8000"
echo "   # Then visit: http://localhost:8000"
echo ""
echo "NOTE: Some features require Firebase connection (internet required)"
echo ""
